# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(choices=[('CO', 'Cold'), ('CH', 'Chilly'), ('NO', 'Normal'), ('WA', 'Warm'), ('HOT', 'Hot')], max_length=2)),
                ('text', models.CharField(max_length=500)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_map.Building')),
            ],
        ),
    ]
