# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
