# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_map', '0002_feedback_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='temp',
            field=models.CharField(choices=[('CO', 'Cold'), ('CH', 'Chilly'), ('NO', 'Normal'), ('WA', 'Warm'), ('HO', 'Hot')], max_length=2),
        ),
    ]
