# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_map', '0003_auto_20170807_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='vote',
            new_name='votes',
        ),
    ]
